project:
  type: website

website:
  title: "Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://github.com/KhushiiChoudhary
        text: Github
        icon: github
        
      - href: https://www.linkedin.com/in/khushichoudhary27/
        text: Linkedin
        icon: linkedin
     
      - href: contact.qmd
        text: Contact
        icon: telephone-fill
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



